GlobalParameters:
  MinimumRequiredVersion: 4.1.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  NumElementsToValidate: 0
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: True
  SleepPercent: 200
  DataInitTypeBeta : 0
  SolutionSelectionAlg: 1  # keepWinnerSolutions

BenchmarkProblems:

  ########################################
  ########################################
  ###
  ###   NN
  ###
  ########################################
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True 

  ########################################
  # NN - NonBatched
  ########################################
    - # Benchmark Group - ResNet 1x1:
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - PrefetchGlobalRead: [ False, True ]
        - PrefetchLocalRead: [ False, True ]
        - ThreadTile:
          - [ 4, 4 ]
          - [ 4, 8 ]
          - [ 8, 4 ]
        - WorkGroup:
          - [ 16,  8, 1 ]
          - [ 8, 32, 1 ]
          - [ 16, 16, 1 ]
          - [ 32,  8, 1 ]
        - WorkGroupMapping: [1, 8]
        - DepthU: [ 8, 16 ]
        - VectorWidth: [1,2,4]
        - GlobalReadVectorWidth: [1,4]
        - LdsPadB: [0,1,2,4]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [  12544,  256, 1, 1024 ]
          - Exact: [  50176,  512, 1,  128 ]
          - Exact: [   3136,  512, 1, 2048 ]
          - Exact: [  12544, 1024, 1,  256 ]
          - Exact: [   3136, 2048, 1,  512 ]
          - Exact: [ 193600,  256, 1,   64 ]
          - Exact: [ 193600,   64, 1,   64 ]

  ########################################
  # NN - Batch
  ########################################
    - # Benchmark Group - ResNet 1x1:
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - PrefetchGlobalRead: [ False, True ]
        - PrefetchLocalRead: [ False]
        - ThreadTile:
          - [ 4, 4 ]
          - [ 4, 8 ]
          - [ 8, 4 ]
        - WorkGroup:
          - [ 16,  8, 1 ]
          - [ 8, 32, 1 ]
          - [ 16, 16, 1 ]
          - [ 32,  8, 1 ]
        - WorkGroupMapping: [8]
        - DepthU: [ 16 ]
        - VectorWidth: [1,2,4]
        - GlobalReadVectorWidth: [1,4]
        - LdsPadB: [0,1,2,4]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [  196,  256, 64, 1024 ]
          - Exact: [  784,  512, 64,  128 ]
          - Exact: [   49,  512, 64, 2048 ]
          - Exact: [  196, 1024, 64,  256 ]
          - Exact: [   49, 2048, 64,  512 ]
          - Exact: [ 3025,  256, 64,   64 ]
          - Exact: [ 3025,   64, 64,   64 ]


LibraryLogic:
    ScheduleName: "vega10"
    DeviceNames: ["Device 6863", "Device 6862", "Device 687f", "Device 6860"]
    ArchitectureName: "gfx900"

#   ScheduleName: "mi25"
#   DeviceNames: ["Device 6860"]
#   ArchitectureName: "gfx900"

#   ScheduleName: "r9nano"
#   DeviceNames: ["Device 7300"]
#   ArchitectureName: "gfx803"

#   ScheduleName: "hip"
#   DeviceNames: ["Device 0000"]
#   ArchitectureName: "fallback"

LibraryClient:
